'''
Created on Wednesday, 06 March 2019
@author: bhs

THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!!!

XML Source: MathOpSerializableAi.xml
'''


# Import the types this way so they do not need prefixing for execution.
from models.serialize.type_exceptions import *
from models.serialize.type_base import *

from models.serialize.bool_type import *
from models.serialize.enum_type import *
from models.serialize.f32_type import *
from models.serialize.f64_type import *

from models.serialize.u8_type import *
from models.serialize.u16_type import *
from models.serialize.u32_type import *
from models.serialize.u64_type import *

from models.serialize.i8_type import *
from models.serialize.i16_type import *
from models.serialize.i32_type import *
from models.serialize.i64_type import *

from models.serialize.string_type import *
from models.serialize.serializable_type import *


class MathOp(SerializableType):


    def __init__(self):
    
        m_list = [
            ("val1",F32Type(),"%g"),
            ("val2",F32Type(),"%g"),
            ("op",EnumType("Operation",{"ADD":0,"SUB":1,"MULT":2,"DIVIDE":3,}),"%s"),
            ("result",F32Type(),"%g"),
        ]
        
        super(MathOp,self).__init__("MathOp",m_list)
                    

